services:

  db:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "wpuser"
      MYSQL_PASSWORD: "wp12345"
    volumes:
      - wp_db:/var/lib/mysql
    restart: unless-stopped

  wordpress:
    image: wordpress:6-apache
    depends_on:
      - db
    ports:
      - "8082:80"
    environment:
      WORDPRESS_DB_HOST: "db:3306"
      WORDPRESS_DB_NAME: "wordpress"
      WORDPRESS_DB_USER: "wpuser"
      WORDPRESS_DB_PASSWORD: "wp12345"
    volumes:
      - wp_files:/var/www/html
    restart: unless-stopped

volumes:
  wp_db:
  wp_files:
